# Generated by Django 4.2.1 on 2023-05-23 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_financialgoal_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='expenses.category'),
        ),
        migrations.AddField(
            model_name='expense',
            name='date',
            field=models.DateField(default='2023-01-01'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default='2023-01-01'),
        ),
    ]
